name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest-arm
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u y2khub --password-stdin
    - run: make
